name: Bug Report
description: Report a bug or issue with the Agent Mesh Protocol
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below to help us understand and reproduce the issue.
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Check our [FAQ](https://docs.agentmeshprotocol.io/faq) for common issues
        - Review our [troubleshooting guide](https://docs.agentmeshprotocol.io/troubleshooting)

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Initialize AMP agent with...
        2. Send message with payload...
        3. Observe error...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (minor inconvenience)
        - Medium (affects functionality)
        - High (blocks major functionality)
        - Critical (system unusable)
    validations:
      required: true

  - type: input
    id: amp-version
    attributes:
      label: AMP Version
      description: Which version of AMP are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: AI Framework
      description: Which AI framework are you using?
      options:
        - LangChain
        - CrewAI
        - AutoGen
        - Custom/Other
        - Not applicable
    validations:
      required: true

  - type: input
    id: framework-version
    attributes:
      label: Framework Version
      description: Version of the AI framework (if applicable)
      placeholder: "0.1.0"

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running AMP?
      options:
        - Development
        - Staging
        - Production
        - Testing
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Python version (if using Python implementation)
      placeholder: "3.9.0"

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your operating system and version
      placeholder: "Ubuntu 20.04 / macOS 12.0 / Windows 11"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages, stack traces, or logs
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant AMP configuration (remove sensitive data)
      placeholder: |
        {
          "protocol": "AMP/1.0",
          "agent": {
            "id": "example-agent",
            "capabilities": [...]
          }
        }
      render: json

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Screenshots
        - Related issues
        - Workarounds tried
        - Network configuration
        - Security settings

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: I have provided all required information
          required: true
        - label: I have removed sensitive information from logs/config
          required: true